import type { Collection } from "tinacms";

export const TeacherCollection: Collection = {
  name: "teacher",
  label: "Teachers",
  path: "content/teachers",
  format: "md",
  fields: [
    { type: "string", name: "name", label: "Name", required: true },
    { type: "string", name: "slug", label: "Slug", required: true },
    {
      name: "languages",
      label: "Languages",
      type: "string",
      list: true,
    },
    { type: "string", name: "totalExperience", label: "Total Experience" },
    {
      type: "string",
      name: "education",
      label: "Education",
      ui: { component: "textarea" },
    },
    {
      type: "object",
      name: "certificates",
      label: "Certificates",
      list: true,
      fields: [{ type: "string", name: "cert", label: "Certificate" }],
    },
    {
      type: "object",
      name: "areasOfWork",
      label: "Areas of Work",
      list: true,
      fields: [{ type: "string", name: "area", label: "Area" }],
    },
    { type: "string", name: "responsibilities", label: "Responsibilities" },
    {
      type: "string",
      name: "resume",
      label: "Resume",
      ui: { component: "textarea" },
    },
    {
      type: "string",
      name: "otherExperience",
      label: "Other Experience",
      ui: { component: "textarea" },
    },
    {
      type: "object",
      name: "consultingTopics",
      label: "Consulting Topics",
      list: true,
      fields: [{ type: "string", name: "topic", label: "Topic" }],
    },
    { type: "string", name: "interests", label: "Interests" },
    {
      type: "string",
      name: "teachingStyle",
      label: "Teaching Style",
      ui: { component: "textarea" },
    },
    {
      type: "object",
      name: "photos",
      label: "Photos",
      list: true,
      fields: [{ type: "image", name: "photo", label: "Photo" }],
    },
    { type: "boolean", name: "isActive", label: "Is Active" },
    { type: "string", name: "body", label: "Bio" },
  ],
};
